name: Android Release Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set up Java Development Kit (JDK) 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Grant Gradle execute permission
      run: chmod +x gradlew

    - name: Perform Android App Verification and Compilation
      run: ./gradlew assembleDebug

    - name: Upload Secure App Artifact (APK)
      uses: actions/upload-artifact@v4
      with:
        name: AmitSafe-Vault
        path: app/build/outputs/apk/debug/app-debug.apk
